### ISSUE TITLE
Installation docs are out of date -- no gpaw for OSX

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#1066]
Our installation page on readthedocs states ["For both Mac Os X and Linux GPAW is available from conda-forge available:"](https://pyiron.readthedocs.io/en/latest/source/notebooks/test_pyiron_installation.html#GPAW). Unfortunately, the conda-forge package [only supports linux](https://anaconda.org/conda-forge/gpaw). When I look back through the files there I don't see that it _ever_ supported OSX.

Is there some other source, or are the docs just wrong? I only really care about having it for mac because I was doing some testing for [pyiron_contrib #694](https://github.com/pyiron/pyiron_contrib/issues/694) -- the ideal solution would be to make GPaw also available on Mac, but from my end it would only be needed for debugging this one issue and is not worth pouring a bunch of time into, so the secondary solution of correcting the docs is also acceptable to me.

**Comment by ligerzero-ai** [comment]
removed mention of GPAW in the docs - it does not seem like the trouble is worth the effort, tbh. Short google led me to this: 

https://gitlab.com/gpaw/gpaw/-/merge_requests/830 

Which makes it seem like running GPAW on OSX is more trouble than it's worth.

**Comment by liamhuber** [comment]
From my perspective this is true, although I think a reasonable person could disagree with us. But the docs are no longer wrong, so I'm happy to close the issue--thanks! 😄

**Comment by liamhuber** [comment]
Ah, nm, I can't figure out how to close from mobile. Will do it later 😝

**Comment by jan-janssen** [comment]
It is not too hard to build the conda-forge Mac OS X package https://github.com/conda-forge/gpaw-feedstock/pull/40 at least for Mac OS X on Intel everything seems to work just fine.

**Comment by ligerzero-ai** [comment]
Opinionated comment:

I feel like by saying it can be offered on both OSX and linux, it may bait users into wasting time into trying to get it to work. 

IMHO there is some obligation to prevent newcomers to the community from wasting time and instead push them to the path of least resistance and the de-facto community standard, which is linux. This includes omitting mentioning the ability for users trying to do (bad) things like running computational atomistics codes on non-linux OS machines. 

It's better to rip off the bandaid of learning linux before they have too much time invested in trying to avoid learning it if they are serious about doing computational atomistics work. 

It also prevents work on both ends, devs trying to support ever-growing architectures and OS combinations (OSX+ARM, WIN+ARM, WIN+x86, OSX+86, LINUX+ARM, LINUX+x86), etc.

 I'm of the mind to remove any mentions of non-linux support because of this.

**Comment by liamhuber** [comment]
> I feel like by saying it can be offered on both OSX and linux, it may bait users into wasting time into trying to get it to work.

I think Jan's point is that _we_ can do the work so that the OSX (on Intel) also runs as easily as `conda install -c conda-forge gpaw`. He's right, I am just very unmotivated to get gpaw running. This is what I was referring to when I said "a reasonable person might disagree" 😉 

>  IMHO there is some obligation to prevent newcomers to the community from wasting time and instead push them to the path of least resistance and the de-facto community standard, which is linux...I'm of the mind to remove any mentions of non-linux support because of this.

I disagree. It isn't just mac-brains and windows-brains who refuse to "learn linux", there are plenty of people (myself included) who just happen to have one of those operating systems installed and use it for other purposes. I am always understanding when a code doesn't support these OSs, but I would find it extremely aggravating if pyiron forced me to dual-boot purely for the sake of "teaching me a lesson".

**Comment by ligerzero-ai** [comment]
I agree, but for those users they are probably more inclined to know exactly how they need to play with something to get it to work - as opposed to people who are the audiences for these specific notebooks, which are more than likely people that are new to pyiron and are testing it. 

Probably my main point is that I am disinclined to introduce a new source of failure which is likely to come from the heterogeneous combinations of architectures + OS. This is more confusing to the user and does no favours to anyone when something is supposed to be run for testing and could fail simply because of it.

Something that is frequented often and well-maintained because of it (i.e. linux GPAW) is probably the way to go for tests. 

This is especially the case when I can see something that is super fiddly as in that 2 year-old long pull that is updated every few months with a new source of failure.

**Comment by liamhuber** [comment]
> It is not too hard to build the conda-forge Mac OS X package https://github.com/conda-forge/gpaw-feedstock/pull/40 at least for Mac OS X on Intel everything seems to work just fine.

@jan-janssen, I appreciate that you did this, but you're going to have to run a tutorial one day where you teach us enough that this looks "not too hard" -- that PR changes 79 files and introduces a whole new file (`.scripts/run_osx_build.sh`) that I have trouble following. I like it, it just would not be easy for me at present!

**Comment by jan-janssen** [comment]
@liamhuber If you look at the individual commits, all I did was changing two lines https://github.com/conda-forge/gpaw-feedstock/pull/40/commits/82270e73e1de4a0211cd2343b1a2871edf6cb578 and afterwards calling `@conda-forge-admin, please rerender` to trigger the automated creation of new continuous integration tasks and so on. This second commit resulted in changing 78 files.

**Comment by jan-janssen** [comment]
I recently gave a talk/ lecture about conda forge which introduces a couple of these tricks: 
https://www.youtube.com/watch?v=P9_uMPyEQrg

**Comment by liamhuber** [comment]
> @liamhuber If you look at the individual commits, all I did was changing two lines [conda-forge/gpaw-feedstock@82270e7](https://github.com/conda-forge/gpaw-feedstock/commit/82270e73e1de4a0211cd2343b1a2871edf6cb578) and afterwards calling `@conda-forge-admin, please rerender` to trigger the automated creation of new continuous integration tasks and so on. This second commit resulted in changing 78 files.

That's amazing. I don't get it then, why hadn't the gpaw admins simply done this already?

**Comment by jan-janssen** [comment]
> That's amazing. I don't get it then, why hadn't the gpaw admins simply done this already?

As I am the `gpaw admin` I guess that one is on me as well, with over 500+ packages I simply lost the overview. Sometimes certain dependencies are only available for linux when I create the package and then I do not get around testing if the dependencies added support for Mac OS X unless there is an external trigger.

**Comment by liamhuber** [comment]
Haha, I didn't mean to Shane you @jan-janssen! I guess this really just pushes the question up a level -- if it's that easy to maintain the conda feedstocks why don't the core gpaw devs (and for many other packages you manage) start and manage it themselves? For me the benefit of being in the conda-forge universe is so big, but maybe it is simply not appreciated broadly enough? As soon as I had packages I was the key responsible person for (ironflow and pyiron_ontology), I sat down and figured out how to do it for simple noarch python stuff and it was really easy. I've always thought managing compiled binaries with different architectures must be multiple times harder, but that would still leave it not that hard... (I'll watch your talk when I get a chance and may have a more informed opinion soon 😅)

**Comment by jan-janssen** [comment]
The apple ARM variant is going to take a little longer as currently `elpa` a library gpaw relies on is not yet available for Apple ARM https://github.com/conda-forge/elpa-feedstock/pull/16
