### ISSUE TITLE
Why are Lammps(?) jobs printing "r"???

### ISSUE THREAD

**Issue by liamhuber** [pyiron/pyiron_atomistics#1284]
I'm not 100% sure yet that it's Lammps-specific. Can anyone reproduce this? I just pulled the bleeding edge of base and atomistics.

<img width="872" alt="Screen Shot 2024-01-04 at 13 51 03" src="https://github.com/pyiron/pyiron_atomistics/assets/20283329/ac8b713e-f8ac-4887-ad7f-6424cded63a7">

**Comment by pmrv** [comment]
Bug from [h5io](https://github.com/h5io/h5io/pull/61).  It's fixed and released, should disappear on the latest releases of h5io. My bad. :S

**Comment by jan-janssen** [comment]
@liamhuber I am a bit surprised that you get this issue with the latest version of `pyiron_base` and `pyiron_atomistics` because those should use a more recent version of `h5io` and `h5io_browser`. The issue you describe was fixed in `h5io=0.1.10` as linked above by @pmrv . @liamhuber Can you share your versions of `pyiron_base`, `pyiron_atomistics` , `h5io` and `h5io_browser` if that is installed?

**Comment by liamhuber** [comment]
@jan-janssen, I didn't install the latest version, I just pulled in the bleeding edge of the repos mentioned -- the problem was on my end as my environment was out of date. @pmrv pointed me to the lagging package and I closed the issue.

I definitely should have updated my env before besmirching `pyiron_atomistics`'s name by opening the issue, but (thanks to Marvin's super speedy advice! 🚀) it was open for less than two hours.
