### ISSUE TITLE
unwrapped_positions

### ISSUE THREAD

**Issue by caglayanoaras** [pyiron/pyiron_atomistics#143]
I have a question rather than an issue. For an 128 atom BCC Ti, If I plot the positions of atoms, I get the figure below:
![wrapped](https://user-images.githubusercontent.com/56139345/112466112-c3bba500-8d65-11eb-99f3-63a03a95526b.PNG)

If I plot the 'unwrapped_positions' I get this figure:

![unwrapped](https://user-images.githubusercontent.com/56139345/112466182-d7ffa200-8d65-11eb-9bf8-180c79600a52.PNG)

Wrapped positions should be within the cell and as a result I find these plots strange. I am suspicious that
'output/generic/positions' gives the unwrapped positions  and
'output/generic/unwrapped_positions' gives the wrapped positions   Which should be the opposite

Any comment is much appreciated.

**Comment by liamhuber** [comment]
It looks fine to me. For instance, if I look at the cluster around (10, 3.5) the `positions` seems to have fewer entries than `unwrapped_positions`. Since you apply a filter $z \in (-0.2, 0.2)$ the `positions` loses all entries that got wrapped around to the top of the supercell at some point, while the unwrapped positions keep everyone who didn't oscillate by >|0.2|. Thus, density(unwrapped) > density(wrapped).

Also note that `wrapped` is 5x5 while `unwrapped` is 4x4. This is because the edge clusters in the wrapped case belong to the same atom, but it spends some of its time wrapped over to the other side of the supercell.

Your `unwrapped` plot looks really good to me, and I find it physically interesting to see that some clusters are quite circularly symmetric while others display rather strong ellipticity.

**Comment by sudarsan-surendralal** [comment]
In addition to what @liamhuber nicely explained, you could also check `np.min(pos[:, :, 0)`, `np.min(pos[:, :, 1)`, `np.max(pos[:, :, 0)`, `np.max(pos[:, :, 1)`. For wrapped positions, these values should be positive but less than the supercell length along that direction.
