### ISSUE TITLE
New mode for `get_neighbors`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#232]
Here I want to talk about a small modification in `get_neighbors` and I would like to know what you guys think.

Currently, `get_neighbors` gives different results depending on `allow_ragged = True` or `False`. This essentially concerns when the cutoff radius is specified and the number of neighbours for each atom is not the same (e.g. first atom has 4 neighbours within a radius `r` and the second atom 5 etc.). The two modes handle such a case as follows:

- `allow_ragged = True`: Create a list of numpy arrays with different lengths
- `allow_ragged = False`: Fill missing entries with impossible elements (`np.inf` in `distances`, `vecs`; `natoms+1` for `indices`; and 0 for `shells`).

As it turned out for me, they were both not particularly useful (and also not elegant). Now I'm wondering what you guys think of doing the distinction as follows:

- `mode = 'flattened'`: Return flattened arrays for `distances`, `vecs` and `shells` (where the filled values are removed) and `(N, 2)`-array for `indices` containing the pairs of indices (first is that of the atom in focus and second is that of the neighbour)
- `mode = 'filled'`: Same as `allow_ragged = False`
- `mode = 'ragged'` Same as `allow_ragged = True`

I could have opened a PR directly but I wanted to know your opinions on this before doing so.

**Comment by sudarsan-surendralal** [comment]
I like the three modes you've suggested (I guess the default more is `filled`?). But I think `distances`, `vecs`, and `indices` should always have the same shape depending on the mode. Rather than changing the shape of `indices` for the `flattened` mode, how about defining a new attribute `atom_number` (feel free to change the name) which indicates the atom under focus? This would have the format like `[0, 1, ..., n_atoms-1]` for the `filled` and `ragged` modes but something like `[0, 0, ..., 1, 1, ..., n_atoms-1, n_atoms-1]` for the `flattened` mode.

**Comment by samwaseda** [comment]
Ok I like the suggestion :) I'm gonna do it this way
