### ISSUE TITLE
more than one SQS structure

### ISSUE THREAD

**Issue by caglayanoaras** [pyiron/pyiron_atomistics#242]
I aim to get 5 SQS structures for BCC Cu-Al solution. I am on MPIE cluster and the code I write is:

> job_sqs = pr.create_job(
    job_type=pr.job_type.SQSJob, 
    job_name='my_sqs',
    delete_existing_job=True,
)
job_sqs.structure = bcc_cu_super
job_sqs.input.mole_fractions = {'Al': 0.1, 'Cu':0.9}
job_sqs.input.iterations = 1000000
job_sqs.input.n_output_structures = 5
job_sqs.run()

However, I only get one structure:
![output](https://user-images.githubusercontent.com/56139345/122775902-e6008880-d2aa-11eb-8eff-9c3f138a3745.PNG)

Am I missing something? I am not super familiar with with SQS structures so any help is appreciated.

**Comment by pmrv** [comment]
How do you create the super cell?

This snippet (which is the same as yours) worked for me

```python
from pyiron import Project
pr = Project('sqs')

job_sqs = pr.create_job(
job_type=pr.job_type.SQSJob,
job_name='my_sqs',
delete_existing_job=True,
)
job_sqs.structure = pr.create.structure.bulk('Al').repeat(3)
job_sqs.input.mole_fractions = {'Al': 0.1, 'Cu':0.9}
job_sqs.input.iterations = 1000000
job_sqs.input.n_output_structures = 5
job_sqs.run()

len(job_sqs.list_of_structures)
```

EDIT: Also seems to work for a bcc super cell.

**Comment by caglayanoaras** [comment]
Could you please also try with 
`pr.create.structure.bulk(name='Cu', crystalstructure='bcc', a=2.8726, cubic=True).repeat(4)
`
It works for 3 but not for 4. 
![Capture](https://user-images.githubusercontent.com/56139345/122796394-a04dbb00-d2be-11eb-82c4-68059f4bfd9c.PNG)

**Comment by pmrv** [comment]
Can reproduce.  That's a weird bug, though.  If I read the `sqsgenerator` source correctly structures are only output if they have a better "random quality"/"alpha" then previously found structures, so I guess in the case of 4x4x4 cubic supercell the very first structure found is already optimal by chance and all later structures are rejected.

Probably a quick work around is to change the supercell size.

@dgehringer Any insight on this? :S

**Comment by liamhuber** [comment]
@liamhuber I want this to show up in my "mentioned" filter as I would be keen to know about a solution too, but don't have time to dig into it.

**Comment by dgehringer** [comment]
@pmrv Indeed you are right! However, this is no bug but rather intended behavior. Nevertheless I agree that the name `n_output_structures`, is misleading a little bit. What it actually does would be better described by  `n_max_output_structures`.

The objective function which *measures the randomness* of a certain configuration is non-injective. Consequently there might be just one or many many structures (depending on size and composition) which are *equally optimal* within the SQS formarlism.

In order to tackle this problem a **fixed size** array of **5** is allocated which hold **up to 5** of those optimal structures. Whenever a configuration with a better objective function arrives the array is cleared (since we are only interested in finding optimal structures), and only stores configurations with the same objective function.

@caglayanoaras This means the programm could find just one optimal configuration. If you want to find more of them you can either increase the supercell size (to make use of non-injectivity and increase configurations space) or just make more configurations. You can also adapt the weights

**Comment by caglayanoaras** [comment]
@dgehringer Thanks for the explanation. I am confused at one point. You suggest me to increase the supercell size, but if @pmrv is right, this should not work right? Because as the cell size gets larger, the chance of getting an optimal structure at the beginning increases.
Using a 3*3*3 cell I can get 5 optimal structures, for 4*4*4 I get 1 and for 5*5*5 I get 1 again. If I define number of iterations as 100000, is it doing this much iterations in any case or is it exiting when the obj function hits a threshold?

**Comment by dgehringer** [comment]
@caglayanoaras No there is not threshold! Your results just arises from pure combinatorics! 10^5 iterations are actually too few, using that large supercell sizes!

Maybe increasing super-cell size is not such a good idea, you're right, sorry my bad :see_no_evil: !

So let's go through your example!
You create a 3 x 3 x 3 supercell where you distribute two species! In total you obtain 54 atoms which are distributes 5 and 49.
In total (neglecting) symmetry have 3162510  = 54!/(49!5!) permutations, you sample roughly 3% of the configurational space. That's fine!

The problem comes to when you advance to 4 x 4 x 4, where you obtain 128 atoms. As your configurational space grows exponentially you are left with ~2*10^17 arrangements, which are samples with "*only*" 10^5 tries. So it is very unlikely to encounter another same configuration, with same objective using that little amount of "*tries*". So the number of iterations is inappropriate to sample the configurational space. (With 5 x 5 x 5 you are left of with ~10^34 permutations)

The number of iterations should roughly scale with the extent of the configurational space, which is usually impractical when going to larger supercell sizes.

But note that computing the objective function scales with O(N^2) 

Hope that helps!

**Comment by caglayanoaras** [comment]
Very clear thank you very much. Closing the issue.

**Comment by pmrv** [comment]
> @pmrv Indeed you are right! However, this is no bug but rather intended behavior. Nevertheless I agree that the name `n_output_structures`, is misleading a little bit. What it actually does would be better described by `n_max_output_structures`.
> 
> The objective function which _measures the randomness_ of a certain configuration is non-injective. Consequently there might be just one or many many structures (depending on size and composition) which are _equally optimal_ within the SQS formarlism.
> 
> In order to tackle this problem a **fixed size** array of **5** is allocated which hold **up to 5** of those optimal structures. Whenever a configuration with a better objective function arrives the array is cleared (since we are only interested in finding optimal structures), and only stores configurations with the same objective function.
> 
> @caglayanoaras This means the programm could find just one optimal configuration. If you want to find more of them you can either increase the supercell size (to make use of non-injectivity and increase configurations space) or just make more configurations. You can also adapt the weights

Thanks for dropping in quickly!
