### ISSUE TITLE
Why isn't `centrosymmetry` not 0?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#267]
The following lines
```
from pyiron import Project
Project('.').create.structure.bulk('Fe', cubic=True).analyse.pyscal_centro_symmetry()
```

produce `array([0.      , 6.177675])`. Why aren't they both 0?

**Comment by samwaseda** [comment]
By the way with Ovito I get the same values.

**Comment by srmnitc** [comment]
@samwaseda I remember this issue came up before, but I cannot find the thread now. In any case, it is because of the number of neighbours selected for the calculation. Here it is N=12; so for bcc, it is atoms of the first shell, and some atoms from the second shell. The CSP calculated then depends on how these extra neighbours are chosen, and it is different for ovito and pyscal. None of these values are correct anyway. For bcc, N=8 or N=14 would be the correct choices, which would give a CSP of 0.

**Comment by samwaseda** [comment]
Ah brilliant! But why doesn't pyscal choose the number of neighbours automatically? (Especially given the fact that it does a great job when it comes to CNA?)

**Comment by srmnitc** [comment]
N is sort of an input parameter; and you can get different information based on the choice of N. So I left it as such :) The default is set to 12, similar to ovito.

**Comment by samwaseda** [comment]
But wouldn't it be more attractive for the user (and possibly demonstrate the full power of pyscal) if the default is `N=None` and pyscal chooses the proper value when the number of neighbours is not specified?

**Comment by srmnitc** [comment]
That is great idea. Also could be done without much trouble. I will have it in one of the future releases!
