### ISSUE TITLE
syntactic sugar for SPHInX input file settings

### ISSUE THREAD

**Issue by freyso** [pyiron/pyiron_atomistics#382]
**Summary**

I want to simplify the setting of sphinx input settings that are deep in the hierarchy like this:
`job.input.sphinx.search_tree ('preconditioner').type = "CSRB"`
instead of
`job.input.sphinx.main.ricQN.bornOppenheimer.scfDiag.preconditioner.type = "CSRB"`
assuming that everything up to and including 'preconditioner' has been created already, and 'type' is the new setting.

A variant could be
`job.input.sphinx['main.**.preconditioner'].type = "CSRB"`

**Detailed Description**
Main motivation: hide some of the complexity of the SPHInX input file from normal users by allowing them to directly apply settings found in the manual, under the condition that the parent group is sufficiently unique (which usually is the case). At present, the hierarchy location of some groups may vary with the type of calculation (optimizer, static calculation), and we don't want pyiron users to care for this.

The search_tree function will search the group hierarchy for the first matching suitable group (depth first). 
I do have a working implementation for search_tree, that should go into _pyiron_atomistics.sphinx.base.Group_ .

I also have a working version for the variant. It works by providing a `__get_item__ function`, scanning for '.' and '**' in the key, and otherwise fall back to DataContainer's implementation.

**My questions**  Any concerns about this from the pyiron look&feel perspective ?

**Comment by pmrv** [comment]
I'd strongly prefer the first version, because it avoids bespoke strings.  I'd even want this as part of the `DataContainer` in pyiron_base.  If you have working code already, it should not be any work at all to add it to `DataContainer` instead of `Group`, but I'll be happy to do the transplant myself, too.

A few open question I still have would be best discussed with the code: depth vs. breadth-first search and what happens on collisions.

**Comment by freyso** [comment]
I have created a pull request in pyiron_base , let's continue discussions there: https://github.com/pyiron/pyiron_base/pull/460
