### ISSUE TITLE
Pressure value difficult to understand

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#486]
Today at the ADIS meeting we realised that it is extremely confusing that `pressure=0` in `calc_minimize` etc. means the hydrostatic pressure, i.e. as long as the total pressure is 0, it doesn't matter whether `p_xx` is 2000 GPa or `p_yy` is -3000 GPa. At the next pyiron meeting we should talk about what it should be called.

**Comment by liamhuber** [comment]
I would actually be super careful about changing the behaviour of `pressure=0`. IIRC, right now `pressure=0` gives hydrostatic, `pressure=[0,0,0]` lets the axes relax independently, and `pressure=0*np.eye(3)` relaxes all DOF. So for `pressure=0` you provide one parameter and this impacts one degree of freedom, etc.

If we switch it so that `pressure=0`=`pressure=0*np.eye(3)`, how do we recover the option for hydrostatic pressure? `pressure=0, but_really_hydrostatic=True`? I'm not totally closed to making adjustments in this place, but let's keep carefully in mind python's third zen point: "complex is better than complicated".

**Comment by samwaseda** [comment]
> If we switch it so that pressure=0=pressure=0*np.eye(3), how do we recover the option for hydrostatic pressure?

Yeah that's the reason why I didn't directly open a PR. On the other hand, we call the average pressure "hydrostatic pressure", but this is physically meaningless as long as the system is not liquid. @JNmpi 's idea was to add `hydrostatic_pressure`. Mine would be to issue a warning whenever a single number is set. Frankly, I would even accept to not offer hydrostatic pressure in the first place.

**Comment by liamhuber** [comment]
Hmm, I think we need to offer it overall-- even if we don't use it there's no reason people doing atomistic fluid simulations shouldn't be supported. And I'm still not in favor of adding extra flags unless we're really completely desperate. I quite like the idea of throwing a warning though.

**Comment by samwaseda** [comment]
Following today's pyiron session, it should look like this:

```python
def calc_minimize(pressure=None, cell_shape=None):
    if pressure is not None:
        if not hasattr(pressure, __len__):
            if cell_shape is None and :
                warnings.warn('cell shape was iso but now aniso')
            cell_shape = 'aniso'
```

**Comment by samwaseda** [comment]
I close it now, because I thought about it a few times after the discussion and I'm actually uncomfortable with any variation that has been discussed, or at least I don't have the feeling that there's more benefit than the damage caused by creating a different default behaviour.
