### ISSUE TITLE
Default smearing routine in SPHInX 

### ISSUE THREAD

**Issue by skatnagallu** [pyiron/pyiron_atomistics#502]
Hello, I want to know which is the default smearing routine used in SPHInX calculations. I was under the impression that this was Fermi-Dirac. But according to my calculations, @freyso and I found that sometimes it is Fermi-Dirac and sometimes it is Methfessel Paxton, even though I never explicitly choose wither of them. This makes it difficult to compare among the calculations. I attaching pictures of two recent calculations where one had Methfessel Paxton of order 1 and other had Fermi Dirac of order 1.
<img width="284" alt="FD" src="https://user-images.githubusercontent.com/85609781/149274626-b393905c-131d-48bf-8145-120b7ea3170e.PNG">
<img width="267" alt="MP" src="https://user-images.githubusercontent.com/85609781/149274630-65d1f40d-51c2-4580-8400-d0fcc820cc30.PNG">

**Comment by samwaseda** [comment]
Since the default is Methfessel-Paxton in VASP, the SPHInX default was changed to it in [this PR](https://github.com/pyiron/pyiron_atomistics/pull/416), since @freyso made it available some time ago. So it's not sometimes the one or the other, but it's depending on which version of pyiron you're using.

But you're right that maybe I should have included a warning or better informed everyone that the default has changed.
