### ISSUE TITLE
Replacement of hdf output by `DataContainer`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#508]
While doing the changes in [this PR](https://github.com/pyiron/pyiron_atomistics/pull/505), I accidentally dropped the support for the conventional dict lookup, because `DataContainer` stores the variables with indices. While I have to admit that I went to far with my refactoring idea, I think we can slowly start thinking about going in this direction anyway. What do you think?

**Comment by pmrv** [comment]
Since `DataContainers` support lazy loading for a while, I'd actually try to push this solution even further and replace the whole `job.output` with a data container and let people navigate that directly.  It's true that using them mucks up the 'traditional' access via strings directly into the HDF, but we could be radical and retcon accesses to `job['output/foo']` to be translated directly to `job.output.foo`.

**Comment by samwaseda** [comment]
Yeah I guess as long as `job['output/foo']` can be uniquely identified it shouldn't break anything that's already there.

**Comment by samwaseda** [comment]
Actually now I decided to overwrite `__getitem__` and parse the key, so the SPHInX output should work in the same way as before.
