### ISSUE TITLE
Help Installing pyiron_atomistics compatible OpenKim Models

### ISSUE THREAD

**Issue by sudarsan-surendralal** [pyiron/pyiron_atomistics#597]
I'd like to install OpenKim models that are not part of the default conda version to be able to use them in some LAMMPS simulations. I have `openkim-models` and `kim-api` installed through conda forge (these are not part of the `pyiron_atomistics` dependencies). According to the openkim documentation, I just need to do something like:

`kim-api-collections-management install user MEAM_LAMMPS_RoyDuttaChakraborti_2021_AlLi__MO_971738391444_000`

This tries to download and compile such potentials. However this fails since it tries to access the 'CMAKE_CXX_COMPILER'. I'd like to know if anyone has tried installing such models on our (cmti cluster) or elsewhere. Is so, did you do something similar? I wouldn't want to add anything to the shared openkim models our cluster if possible 

PS: This may not be the right page to post this but I'd expect some useful answers from the developers here.

**Comment by jan-janssen** [comment]
The potentials in openkim are compiled binaries, so you need a c++ compiler and cmake.

**Comment by Leimeroth** [comment]
As mentioned in my mail already I have a manually compiled version of Lammps and Openkim, because I needed some special packages in lammps and the conda-forge version of openkim didn't work. The best idea probably is to install cmake and try again. A c++ compile should always be available already I assume.

I don't really remember the error messages I got with conda-forge OpenKim. Whenever I manually installed someone I tried to make notes to be able to set everything up again and the only thing I wrote down for openkim is the cmake command:

`cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX`

I think the important part was to set the INSTALL_PREFIX to $CONDA_PREFIX to have everything in the correct path after manual installation.

**Comment by pmrv** [comment]
If you want to run on cmti, I'd suggest to do it outside conda, because it tends to mess with everything.  I built openkim potentials already for the cmti build of lammps, but I have to check my notes which and where I put them.

**Comment by sudarsan-surendralal** [comment]
Thanks @Leimeroth, I too have problems with the conda-forge version so I'm doing this manually. @pmrv, yeah I'm first trying this out in my local PC and not cmti. It'll be great if you could share your installation notes if you find them

**Comment by pmrv** [comment]
Here is what I used to build OpenKIM for the cluster lammps
```bash
KIM_INSTALL_DIR=kim
mkdir -p ${KIM_INSTALL_DIR}
cd ${KIM_INSTALL_DIR}
KIM_VER=2.2.1
wget http://s3.openkim.org/kim-api/kim-api-${KIM_VER}.txz
tar xf kim-api-${KIM_VER}.txz
cd kim-api-${KIM_VER}
mkdir -p build && cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${KIM_INSTALL_DIR}
make -j2
make -j2 install
cd ../..
source ${KIM_INSTALL_DIR}/bin/kim-api-activate
kim-api-collections-management install system OpenKIM
rm -f kim-api-${KIM_VER}.txz
rm -f kim-api-${KIM_VER}
```
assuming you have a compiler set up.  Double check that conda is not messing with your environment, I've used
```bash
# Performing condaectomy on a live patient...
export PATH=$(echo $PATH|tr : "\n"|grep -v anaconda|tr "\n" :)
export LD_LIBRARY_PATH=$(echo $LD_LIBRARY_PATH|tr : "\n"|grep -v anaconda|tr "\n" :)
unset LDFLAGS_USED
unset CFLAGS_USED
unset CXXFLAGS_USED
```
to remove traces left after running `conda deactivate`.

**Comment by pmrv** [comment]
@sudarsan-surendralal Is this still relevant?

**Comment by sudarsan-surendralal** [comment]
> @sudarsan-surendralal Is this still relevant?

No not really. I'll close this
