### ISSUE TITLE
How to assign force to SxExtOptInteractive job

### ISSUE THREAD

**Issue by usaikia** [pyiron/pyiron_atomistics#615]
I created a  job pr.create.job.SxExtOptInteractive("test") and assigned a structure to this job. I have a set of forces for this structure from a previous Sphinx static job. Now, I want to assign this set of force as initial input for the SxExtOptInteractive job and relax the structure. Is there any way to do this in pyiron?

**Comment by jan-janssen** [comment]
An `SxExtOpt` Example is available in the `sphinx` examples https://github.com/pyiron/pyiron_atomistics/blob/master/notebooks/tests_sphinx_sphinx_check_all.ipynb
```
spx = pr.create_job('Sphinx', 'spx_sxextopt_Fe')
spx.structure = pr.create_structure('Fe', 'bcc', 2)
spx.structure.set_initial_magnetic_moments([2, 2])
spx.server.run_mode.interactive = True
spx.calc_static()
sxextopt = pr.create_job('SxExtOptInteractive', 'sxextopt_Fe')
sxextopt.ref_job = spx
sxextopt.run()
```

**Comment by samwaseda** [comment]
If you are talking about simply minimising the energy of a single structure with a single static calculation, what @jan-janssen wrote is the simplest way to go.

From what I understood in the discussion with you, you want to do the force mixing outside SxExtOpt, correct? That on the other hand is a slightly tricky problem, because `SxExtOpt` does not offer the possibility to give an update to the current Hessian (or in other words, there's no possibility to set a Hessian externally and update it). I guess the most pragmatic way to go would be to keep track of all forces, and then insert them into `SxExtOpt`, whenever you have new results. For this, you can use [SxExtOpt](https://github.com/pyiron/pyiron_atomistics/blob/0c263c0ec034a9bf00306a58908cdf844e0afec5/pyiron_atomistics/interactive/sxextoptint.py#L31), which is a separate python class inside the same folder as `SxExtOptInteractive`.

This being said, I personally totally abandoned `SxExtOpt`, because with pyiron you can easily determine an approximate Hessian with an interatomic potential (which is probably much better than a simple diagonal matrix), which you can make sense of if you write your own update routines.

**Comment by jan-janssen** [comment]
```python
from pyiron_interactive.sxextoptint import SxExtOpt

sext = SxExtOpt(structure=job.structure, 
                working_directory=Project('interactive').path, 
                maxDist=5, 
                ionic_steps=1000, 
                ionic_energy=1.0e-8, 
                ionic_forces=1.0e-8)

while number_of_steps < ionic_steps and not sext.converged:
    print('step number ', number_of_steps)
    job.structure.positions = new_positions
    job.run()
    # print(np.array(ham.output.forces[-1][0]))
    forces = np.array(job.output.forces[-1]) 
    print(forces)
    sext.set_forces(forces=forces)
    new_positions_temp = sext.get_positions()
    print(new_positions_temp)
    if np.allclose(new_positions, new_positions_temp, rtol=1e-15, atol=1e-15):
        print('all close')
    new_positions = new_positions_temp
    number_of_steps += 1
```

**Comment by usaikia** [comment]
@jan-janssen and @samwaseda thank you for your answers. I want to do SSA relaxation for a paramagnetic grain boundary system as explained in Figure 1 of this paper https://journals.aps.org/prb/pdf/10.1103/PhysRevB.102.144101. According to this paper first I have a take N number of magnetic sqs of the same system and run Sphinx constrain magnetic moments scf calculations for each of them. Next, collect the forces from each calculations and take average. Now I have to assign this averaged forces to the sqs structures and perform ionic relaxation with SxExtOpt. With the relaxed ionic positions from SxExtOpt I have to again perform scf with Sphinx for each magnetic configuration and take average of the forces. I have to repeat this cycle until the averaged forces are converged below my required cutoff.

**Comment by samwaseda** [comment]
There's nothing implemented in pyiron beyond what I described in my last comment, and it's rather unlikely that we're gonna include one-step update, because in @freyso's implementation of SxExtOpt, there's neither a possibility to restart the minimiser, nor the possibility to set the positions from outside. Setting the forces one after another, as I said, is a possibility, but conceptually it's too dangerous and I wouldn't offer it in pyiron.

**Comment by usaikia** [comment]
@samwaseda thank you for the clarification.
