### ISSUE TITLE
How is it possible that `ExampleJob` works here even though it's defined in `pyiron_atomistics`?

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron_atomistics#787]
https://github.com/pyiron/pyiron_atomistics/blob/3035031f125ee011696c511db8e88085b1827e20/tests/testing/test_exampleJob.py#L8-L18

Here only `pyiron_base` is imported, but somehow `ExampleJob` seems to be working, which is defined only in `pyiron_atomistics`. On my branch it namely didn't work. I don't understand how it's possible.

**Comment by niklassiemer** [comment]
Actually, all our jobs in the queue are spinning up _only_ from the command line client as defined in base only! The JobType(Choice) class imports the needed JobClass to deserialize the hdf information and run the calculation. Therefore, any defined job should run by only importing base which imports the rest (of course the definitions of the job have to be importable!)

**Comment by samwaseda** [comment]
hhmmm I'm not sure if I understand it... Does it mean I can also replace `from pyiron_base import Project` by `from pyiron_atomistics import Project`?

**Comment by niklassiemer** [comment]
In principle this is correct! E.g.
```python
from pyiron_base import Project, JobType
JobType.register('pyiron_atomistics.lammps.lammps', job_name='Lammps')
pr = Project('tt')
job = pr.create.job.Lammps('test')
```
provides you with a lammps job, which is, of course, imported from `atomistics.lammps.lammps` in this case. However, the `pr` does not know about structure generation or the like! 
For an already serialized calculation, it is even easier:
```python
from pyiron_base import Project
pr = Project('with_lammps_calculation')
job = pr.load('test')
```
where the job is now a lammps job (given 'test' was one of course).

For the `pr.create.job.JobType` to work, the `JOB_CLASS_DICT`/`JobType` needs the correct entries which are currently populated on import of other pyiron modules like `pyiron_atomistics`.
Thus, w.r.t. the problem in this test I have to revert my claim. It is indeed code smell, since this test cannot be run on a clean interpreter. One needs to have imported `pyiron_atomistics` at any time before (this is usually the case for the full test suite, but not if you only run the single test file)...
