### ISSUE TITLE
using pyiron to perform nudged elastic band calculations

### ISSUE THREAD

**Issue by jyang2009** [pyiron/pyiron_atomistics#826]
Dear all,

I'm trying to perform some nudged elastic band calculations based on phonopy but couldn't find how to do it via pyiron (I checked the example notebook here)[https://pyiron.readthedocs.io/en/latest/source/notebooks/phonopy_example.html](url)
I'm wondering if any of you know if this is implemented and if I could find an example. Thanks a lot.

Best,
Jing

**Comment by liamhuber** [comment]
You can run NEB with an arbitrary force/energy calculator (e.g. VASP, LAMMPS, ...anything implemented in pyiron) using the `NEB` protocol [over in `pyiron_contrib`](https://github.com/pyiron/pyiron_contrib/blob/master/pyiron_contrib/protocol/compound/nudged_elastic_band.py).

If you're using LAMMPS or some other classical MD, where individual force/energy calculations are extremely fast and cheap, there might be a more efficient solution -- the protocol really runs the NEB part right in python (which is why it works with any pyiron-wrapped atomistic force/energy calculator). I know some of the codes (e.g VASP) has built-in NEB abilities, but I'm not sure if we expose those in pyiron anywhere.

**Comment by liamhuber** [comment]
@raynol-dsouza can you offer guidance or an example of how to actually use it?

**Comment by raynol-dsouza** [comment]
@jyang2009 [here you can find an example](https://github.com/pyiron/pyiron_contrib/blob/master/notebooks/protocol_neb_example.ipynb) of how to run an NEB simulation using the NEB protocol. It was written to run with LAMMPS, but I also remember testing it with vasp. As long as the reference job is set correctly, it should run. Fair warning though, the code is quite old and I haven't really updated it in a very long time, so if you face any difficulties running it, please let me know.

**Comment by samwaseda** [comment]
If you already know that transition path, you can also use the [Quasi Newton method](https://github.com/pyiron/pyiron_atomistics/blob/master/pyiron_atomistics/interactive/quasi_newton.py), which is a lot cheaper than NEB.

**Comment by jyang2009** [comment]
@raynol-dsouza 
Dear Raynol,

I've checked the notebook you sent. I had some difficulties in adapting the workflow to vasp jobs. It seems that the default of job_type.ProtoNEBSer runs in interactive mode, but for vasp jobs I would need to submit all the jobs to the queueing system. I'm not sure whether this is supported. Could you please let me know? Thanks a lot. 

Best,
Jing

**Comment by raynol-dsouza** [comment]
@jyang2009 If I recall correctly, the job itself (ProtoNEBSer) is submitted to the queue and it should handle the individual bead jobs internally. I can check it once again and get it running, however, I am a bit swamped this week with some personal obligations in addition to regular work and would only be able to get to it next week. Meanwhile, I would suggest you look at the Quasi Newton method that @samwaseda has implemented recently if it suits your application. As Sam mentioned, it is definitely much more efficient if you just want to find the transition barrier.

**Comment by liamhuber** [comment]
@jyang2009, what is the status of this, can we close the issue? 

I suspect the most computationally efficient approach is to use Quasi Newton as suggested by Sam.

In case you do go with NEB, I'm afraid I don't understand what the problem is.

> It seems that the default of job_type.ProtoNEBSer runs in interactive mode

Protocols inherit from generic job and run non-interactively; you should be able to submit them to the queue as normal.

The *children* of protocols, e.g. individual Lammps and Vasp calculations do indeed run in interactive mode. As far as I know, Vasp interactive is working fine.

> for vasp jobs I would need to submit all the jobs to the queueing system.

Absolutely. For cheap Lammps calculations the NEB protocol calculates the individual images in series, but for expensive calculators like VASP these are run in parallel. As far as I can tell, you should be able to run each image on multiple cores, e.g. `ref_job.server.cores = 8`, just make sure sure that the protocol has access to $n_{cores per image} \times n_{images}$ cores, e.g. if each ref job gets 8 cores and we have five images, `neb_job.server.cores = 40`.

You can then submit the entire NEB job to the cluster like any other job.

>  I'm not sure whether this is supported. Could you please let me know? 

I've made a slightly updated example below. I'm having trouble logging into the cluster so I can't check the submission part. Please:
- run it
- modify it so it submits to the queue and run it again
- Further modify it so it uses VASP instead of LAMMPS and run it again
  - You probably want to crank all the settings *way* down since this is just a test (2x2x2 cell, 3 images, 1x1x1 kpoints, low ENCUT)

If it fails at any point and you don't understand why, please post as much data here as possible, e.g. the full stack trace for any error messages.

I'm having trouble both logging into the cluster and with pylammpsmpi on my local machine, so I'll try to check this later...but hopefully this runs ok in garching:

```python
from pyiron import Project

pr = Project('neb_example')
pr.remove_jobs_silently(recursive=True)

box = pr.create.structure.bulk('Al', cubic=True).repeat(3)
start = box.copy()
vac_start_loc = start.pop(0)
end = box.copy()
vac_end_loc = end.pop(1)
print(len(box), len(start), len(end))
print(vac_start_loc.position, vac_end_loc.position)
# Pop was successful; migration path is along <011>; all good
# For this example just use unrelaxed endpoints...
# In a real calculation you'd need to relax these first!


cores_per_image = 2

neb_ref = pr.create.job.Lammps('ref_job')
neb_ref.structure = start.copy()
neb_ref.potential = neb_ref.list_potentials()[0]  # Replace with DFT setup (kpoints, etc)
neb_ref.server.cores = cores_per_image
neb_ref.save()  # Don't forget this step!!!


number_of_images = 7

neb_job = pr.create.job.ProtoNEBSer('neb_job')
neb_job.input.ref_job_full_path = neb_ref.path
neb_job.input.structure_initial = start.copy()
neb_job.input.structure_final = end.copy()
neb_job.input.n_images = number_of_images
# You can go look at the [other input options]()
# Here I'll leave them default

neb_job.server.cores = cores_per_image * number_of_images
# neb_job.server.queue = 'cm'  # If it works on the head node, next try this

neb_job.run()

neb_job.plot_elastic_band()
# Start and end point look funny because we didn't bother relaxing them

some_child_name = neb_job.graph.vertices.calc_static.children[1].input.job_name
some_child = pr.load(some_child_name)
print(neb_job.server.cores, some_child.server.cores)
# Children are indeed being instantiated from the ref job with all their cores

# Next go back and try it submitting the queue (uncomment the neb_job.server line above)
# Finally, go back and do it all with ref_job as a VASP job
```

**Comment by jyang2009** [comment]
Dear Liam,

Yes it seems to be working for me now. I will close this issue. Thanks a lot for your help.

Best,
Jing

**Comment by sinazadeh** [comment]
> ```python
> from pyiron import Project
> 
> pr = Project('neb_example')
> pr.remove_jobs_silently(recursive=True)
> 
> box = pr.create.structure.bulk('Al', cubic=True).repeat(3)
> start = box.copy()
> vac_start_loc = start.pop(0)
> end = box.copy()
> vac_end_loc = end.pop(1)
> print(len(box), len(start), len(end))
> print(vac_start_loc.position, vac_end_loc.position)
> # Pop was successful; migration path is along <011>; all good
> # For this example just use unrelaxed endpoints...
> # In a real calculation you'd need to relax these first!
> 
> 
> cores_per_image = 2
> 
> neb_ref = pr.create.job.Lammps('ref_job')
> neb_ref.structure = start.copy()
> neb_ref.potential = neb_ref.list_potentials()[0]  # Replace with DFT setup (kpoints, etc)
> neb_ref.server.cores = cores_per_image
> neb_ref.save()  # Don't forget this step!!!
> 
> 
> number_of_images = 7
> 
> neb_job = pr.create.job.ProtoNEBSer('neb_job')
> neb_job.input.ref_job_full_path = neb_ref.path
> neb_job.input.structure_initial = start.copy()
> neb_job.input.structure_final = end.copy()
> neb_job.input.n_images = number_of_images
> # You can go look at the [other input options]()
> # Here I'll leave them default
> 
> neb_job.server.cores = cores_per_image * number_of_images
> # neb_job.server.queue = 'cm'  # If it works on the head node, next try this
> 
> neb_job.run()
> 
> neb_job.plot_elastic_band()
> # Start and end point look funny because we didn't bother relaxing them
> 
> some_child_name = neb_job.graph.vertices.calc_static.children[1].input.job_name
> some_child = pr.load(some_child_name)
> print(neb_job.server.cores, some_child.server.cores)
> # Children are indeed being instantiated from the ref job with all their cores
> 
> # Next go back and try it submitting the queue (uncomment the neb_job.server line above)
> # Finally, go back and do it all with ref_job as a VASP job
> ```

Running this code for vasp raises the following warning:
```
UserWarning: input_only conflicts new_database_entry; setting new_database_entry=False
  warnings.warn(
```
And it creates neb_job_initialize_jobs_0_hdf5 folder and will finish the calculations for this step. It makes neb_job_initialize_jobs_1_hdf5 folder with POSCAR, POTCAR, INCAR, and KPOINTS, but it cannot start the calculations. Do you have any idea why this happens?
