### ISSUE TITLE
Sphinx Warning: "Warning: non-exponential decay in core"

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#828]
I've noticed that in the sphinx calculations I'm running most jobs contain a lines like

```
effective G basis cutoff: 88.164
Lookup ionic mass of Ca: 40.08
Warning: non-exponential decay in core.
Core is truncated at r=9.46988
```

early in the run.  I'm wondering what the warning means.  Is there initial electron density near the core or does it purely refer to the shape of the pseudo potential? This does not seem cause any problems, but I'm just curious what it means (and didn't find it mentioned in the manual).  Can you explain @samwaseda @freyso ? Thanks!

**Comment by freyso** [comment]
You can safely ignore this.
This occurs in the Vasp PAW reader. Vasp potentials provide the real-space atom-centered data (densities, potentials, wave functions, projectors, etc.) only up to the PAW radius. Within SPHInX, however, I need them also outside (If I remember correctly, because I compute the atom-centered electrostatic terms in a different way than VASP does).
For the core density, I do this extension beyond PAW cutoff by Fourier transforming the reciprocal-space form given in the VASP potential file. However, due to truncation in reciprocal space, these Fourier-transformed densities develop oscillations below a certain threshold that produce problematic artifacts later on. Therefore, I replace the tails of the density by an exponential when they fall below 1e-6 for the first time when moving out from the PAW radius. This exponential is fitted to the previous two points.
The warning is triggered if this fitted exponential is not a positive decaying one, i.e., if either the density is negative (whoooo) or if it is locally increasing. In this case, I forget about the tail and set everything beyond this point to exactly zero, and the warning informs me about it just in case this pragmatic solution ever creates real problems.
I note in passing that all artifacts that I produce beyond the PAW radius are the same in pseudo and all-electron terms, so they should cancel in principle.
Sounds complicated? Yes, that's true. That's why it took me weeks to read in the VASP potential files and produce stable SPHInX results from them.

**Comment by pmrv** [comment]
I was in vacation so I didn't reply earlier, but thanks for clearing it up!
