### ISSUE TITLE
ElasticMatrixJob vs. ElasticTensor

### ISSUE THREAD

**Issue by pmrv** [pyiron/pyiron_atomistics#866]
Is there any good reason we keep `ElasticMatrixJob` around?

**Comment by samwaseda** [comment]
I guess this question matters only in our case, because I don't think `ElasticMatrixJob` is publicly available.

There are still two problems in `ElasticTensor`. One is that there is no possibility to use the smallest number of simulation boxes to get the elastic tensor. This can in principle be done by simply checking the number of independent elastic constants. The other one is that it fails to recognise the internal symmetry when the box symmetry is not properly recognised. The simplest example is when you have a simple bcc cell and repeat it in one direction. Since there is no box symmetry along this direction with the other two directions, the symmetrisation does not take place.

This being said, these problems would be solved by simply increasing the number of calculations, which is usually computationally not very expensive.

Other than the problems above, I don't think there's a good reason to keep `ElasticMatrixJob`.

**Comment by pmrv** [comment]
Ah, I didn't know it's from `pyiron_mpie`.  It only came up because a new user found an example with it and there were some errors.
