### ISSUE TITLE
Moving yaff and quickff to pyiron_gpl

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_atomistics#91]
@SanderBorgmans Based on the strict interpretation of the `GPL` license it is not allowed to include a `GPL` library in an `BSD` licensed project. This is solved by the `LGPL`. So my suggestion would be to migrate `yaff` and `quickff` to `pyiron_gpl`. From the user side nothing changes as long as you import `pyiron`, because both `pyiron_atomistics` and `pyiron_gpl` are loaded in the background when they are installed. But when the user only loads `pyiron_atomistics` they have to separately import `pyiron_gpl`.

**Comment by SanderBorgmans** [comment]
@jan-janssen Sounds fine to me. I'll have to take a look at the changes within pyiron soon, as it has been some time since I compared to the master branch (and I have seen/heard of many changes). There have been some updates to the hpc_ugent_2020 branch, in particular I have been looking at QChem and Raspa, which hopefully should have a basic plugin implemented in a couple of months.

**Comment by jan-janssen** [comment]
Sounds good then I go ahead with the migration.
